export const Timezones = [
    {"label":"(GMT-09:00) US/Alaska","value":"US/Alaska"},
    {"label":"(GMT-08:00) US/Pacific","value":"US/Pacific"},
    {"label":"(GMT-07:00) US/Arizona","value":"US/Arizona"},
    {"label":"(GMT-06:00) US/Central","value":"US/Central"},
    {"label":"(GMT-05:00) US/Eastern","value":"US/Eastern"},
    {"label":"(GMT-04:00) Canada/Atlantic","value":"Canada/Atlantic"},
    {"label":"(GMT-03:30) Canada/Newfoundland","value":"Canada/Newfoundland"},
    {"label":"(GMT-03:00) America/Sao_Paulo","value":"America/Sao_Paulo"},
    {"label":"(GMT-02:00) America/Noronha","value":"America/Noronha"},
    {"label":"(GMT-01:00) Atlantic/Azores","value":"Atlantic/Azores"},
    {"label":"(GMT+00:00) Greenwich Time","value":"Etc/Greenwich"},
    {"label":"(GMT+01:00) Europe/Amsterdam","value":"Europe/Amsterdam"},
    {"label":"(GMT+02:00) Europe/Helsinki","value":"Europe/Helsinki"},
    {"label":"(GMT+03:00) Europe/Moscow","value":"Europe/Moscow"},
    {"label":"(GMT+04:00) Asia/Baku","value":"Asia/Baku"},
    {"label":"(GMT+05:00) Asia/Karachi","value":"Asia/Karachi"},
    {"label":"(GMT+06:00) Asia/Karachi","value":"Asia/Dhaka"},
    {"label":"(GMT+06:30) Asia/Rangoon","value":"Asia/Rangoon"},
    {"label":"(GMT+07:00) Asia/Bangkok","value":"Asia/Bangkok"},
    {"label":"(GMT+08:00) Asia/Kuala_Lumpur","value":"Asia/Kuala_Lumpur"},
    {"label":"(GMT+09:00) Asia/Seoul","value":"Asia/Seoul"},
    {"label":"(GMT+09:30) Australia/Adelaide","value":"Australia/Adelaide"},
    {"label":"(GMT+10:00) Australia/Brisbane","value":"Australia/Brisbane"},
    {"label":"(GMT+11:00) Asia/Magadan","value":"Asia/Magadan"},
    {"label":"(GMT+12:00) Pacific/Auckland","value":"Pacific/Auckland"},
    {"label":"(GMT+12:00) Pacific/Fiji","value":"Pacific/Fiji"},
    {"label":"(GMT+13:00) Pacific/Tongatapu","value":"Pacific/Tongatapu"}
]
